# Generated by Django 4.2 on 2025-08-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('shift_hours', models.IntegerField()),
                ('past_week_hours_raw', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance_km', models.FloatField()),
                ('traffic_level', models.CharField(max_length=16)),
                ('base_time_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('num_drivers', models.IntegerField()),
                ('start_time', models.CharField(max_length=10)),
                ('max_hours', models.IntegerField()),
                ('total_profit', models.FloatField()),
                ('efficiency_score', models.FloatField()),
                ('on_time_deliveries', models.IntegerField()),
                ('late_deliveries', models.IntegerField()),
                ('total_fuel_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('value_rs', models.IntegerField()),
                ('delivery_time_min', models.IntegerField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.route')),
            ],
        ),
    ]
