services:
  - type: web
    name: greencart-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python manage.py migrate && python manage.py load_csvs && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False