services:
  - type: web
    name: greencart-backend
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python manage.py migrate && python manage.py load_csvs && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: greencart-mysql
          property: connectionString